---
# UFW Configuration
- name: "UFW - Allow HTTP and MySQL port"
  ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - "{{ http_port }}"
    - "{{ mysql_port }}"
  tags: [ system ]

# WordPress Configuration
- name: Download and unpack latest WordPress
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"
  tags: [ wordpress ]

- name: Set ownership
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    recurse: yes
    owner: www-data
    group: www-data
  tags: [ wordpress ]

- name: Set permissions for directories
  shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type d -exec chmod 750 {} \\;"
  tags: [ wordpress ]

- name: Set permissions for files
  shell: "/usr/bin/find /var/www/{{ http_host }}/wordpress/ -type f -exec chmod 640 {} \\;"
  tags: [ wordpress ]

- name: Check if wp-cli exists
  stat:
    path: "/usr/local/bin/wp"
  register: wpcli_exist
  tags: [ wordpress ]

- name: Updating wp-cli
  shell: "/usr/local/bin/wp cli update --yes"
  when: wpcli_exist.stat.exists
  tags: [ wordpress ]

- name: Download wp-cli
  get_url:
    url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
    dest: "/usr/local/bin/wp"
    force_basic_auth: yes
    mode: 0755
  when: not wpcli_exist.stat.exists
  tags: [ wordpress ]

- name: Add user to sudoers file
  lineinfile:
    path: /etc/sudoers
    line: 'root ALL=(www-data) NOPASSWD: /usr/local/bin/wp'
    validate: 'visudo -cf %s'
  tags: [ wordpress ]

- name: WP database configuration
  command: "sudo -u www-data /usr/local/bin/wp core config --dbhost={{ mysql_host }} --dbname={{ mysql_db }} --dbuser={{ mysql_user }} --dbpass={{ mysql_password }}"
  args:
    chdir: "/var/www/{{ http_host }}/wordpress/"
  tags: [ wordpress ]

- name: Set up wp-config
  template:
    src: "files/wp-config.php.j2"
    dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
  tags: [ wordpress ]

- name: WP core installation
  command: "sudo -u www-data /usr/local/bin/wp core install --url={{ wp_url }} --title={{ wp_title }} --admin_name={{ wp_admin }} --admin_password={{ wp_password }} --admin_email={{ wp_email }}"
  args:
    chdir: "/var/www/{{ http_host }}/wordpress/"
  tags: [ wordpress ]

- name: Install WP plugins
  command: "sudo -u www-data /usr/local/bin/wp plugin install {{ item }} --activate"
  loop: [ calculated-fields-form ]
  args:
    chdir: "/var/www/{{ http_host }}/wordpress/"
  tags: [ wordpress, wp-cli ]
